WTE-18 upgrade to API 34 + add downloadAndOpenFile function
workindia/RapidWebView pull request #18
Opened 2024-09-05 06:59 UTC by krishna-kudari

- Upgraded library to API 34 Android 14.0 UpsideDownCake.
- Upgraded sample app to API 34 Android 14.0 UpsideDownCake.
- Added DownloadAndOpenFile Functionality to RapidWebViewJSInterface.
- Updated the same on RapidWebViewDocSite.
- Updated the ShowNotification function to handle "POST_NOTIFICATIONS" permission on Android 13.0+ devices
- Updated uploadFile function to handle Media Permissions on Android 13.0+ devices
- updated the uploadFile function js-demo page with dummy url.
- Done testing on Emulator and Android 14 device -> 🔗 [https://docs.google.com/spreadsheets/d/1osBbXHca-vv9j8_M6_Ag60oo79m22T4PEDNasyFNEqU/edit?gid=2090795369#gid=2090795369](url)

2024-09-05 07:05 UTC, krishna-kudari commented on samples/RapidWebViewSdkDocsSite/pages/examples/js-demo.tsx
> +      app.uploadFile("doc","https://google.com/pagead/form-data/1039234079?gtm=45be48s0v9166926293za200&gcd=13l3l3l3l1l1&dma=0&tag_exp=0&npa=0&frm=0&auid=1101065353.1725344348&uaa=arm&uab=64&uafvl=Ch
test file upload link  for demo, working fine as of now. ( will remove if not needed )

2024-09-05 07:06 UTC, krishna-kudari commented on samples/RapidWebViewSdkDocsSite/pages/examples/js-demo.tsx
> +      app.downLoadFileLocally("https://s29.q4cdn.com/175625835/files/doc_downloads/test.pdf","","PUBLIC_DOWNLOADS");
test file download link for demo, works fine as of now ( will remove if not needed )

2024-09-05 07:07 UTC, krishna-kudari commented on samples/RapidWebViewSdkDocsSite/pages/examples/js-demo.tsx
> +      app.downLoadAndOpenFile("https://s29.q4cdn.com/175625835/files/doc_downloads/test.pdf","","PUBLIC_DOWNLOADS");
test file download link for demo, works fine as of now ( will remove if not needed )

2024-09-10 15:58 UTC, nogoodusername requested changes

2024-09-10 15:58 UTC, nogoodusername commented on RapidWebView/src/main/java/in/workindia/rapidwebview/RapidWebViewJSInterface.kt
> +        downloadLocation: String? = DownloadLocation.PUBLIC_DOWNLOADS.name,
All the three parameters should be non-nullable.

2024-09-10 15:58 UTC, nogoodusername commented on RapidWebView/src/main/java/in/workindia/rapidwebview/RapidWebViewJSInterface.kt
> +        }
We don't need this as long as null safety is disabled

2024-09-10 15:58 UTC, nogoodusername commented on RapidWebView/src/main/java/in/workindia/rapidwebview/utils/RapidBrodCastActionUtility.kt
> +        Toast.makeText(context, "Download Complete", Toast.LENGTH_SHORT).show()
Instead of showing Toast message, send a `generateJavaScriptEvent` so the developers can handle it as per their taste.

2024-09-10 15:58 UTC, nogoodusername commented on RapidWebView/src/main/java/in/workindia/rapidwebview/utils/RapidBrodCastActionUtility.kt
> +        )
This function is no longer following single responsibility principle. Rework is required.

2024-09-10 15:58 UTC, nogoodusername commented on RapidWebView/src/main/java/in/workindia/rapidwebview/utils/RapidBrodCastActionUtility.kt
> +                        "status" to "failure"
Pass the `uploadUrl`, `uploadFilename` even in case of `failure`

2024-09-10 15:58 UTC, nogoodusername commented on RapidWebView/src/main/java/in/workindia/rapidwebview/utils/RapidDownLoadUtility.kt
> +        url: String?,
`context` should be the first parameter.

Why would the url and filename be null safe?

2024-09-10 15:58 UTC, nogoodusername commented on RapidWebView/src/main/java/in/workindia/rapidwebview/utils/RapidPermissionHelper.kt
> +    fun requiredPermissionsForReadAndWrite(): Array<String> {
Read and Write of what?? Could be file, SMS, calllog? Please specify clearly in the name

2024-10-01 07:09 UTC, nogoodusername commented on RapidWebView/src/main/AndroidManifest.xml
> +    <uses-permission android:name="android.permission.FOREGROUND_SERVICE"/>
This is an optional permission (part of JS Interface), please remove it from the package's declaration and add it in the documentation that the developer implementing this JS Interface has to include these permissions in their app manifest.

2024-10-01 09:39 UTC, nogoodusername commented on RapidWebView/src/main/AndroidManifest.xml
> -    <uses-permission android:name="android.permission.VIBRATE" />
👍

2024-10-01 10:31 UTC, nogoodusername reviewed
Please resolve these final set of comments

2024-10-01 10:31 UTC, nogoodusername commented on RapidWebView/src/main/java/in/workindia/rapidwebview/RapidWebViewJSInterface.kt
>          }
Move the declaration inside `init`

2024-10-01 10:31 UTC, nogoodusername commented on RapidWebView/src/main/java/in/workindia/rapidwebview/RapidWebViewJSInterface.kt
> +        LocalBroadCastActionUtility.registerReceiver(
`LocalBroadCastActionUtility` -> `LocalBroadcastActionUtility`

2024-10-01 10:31 UTC, nogoodusername commented on RapidWebView/src/main/java/in/workindia/rapidwebview/RapidWebViewJSInterface.kt
> +    fun downloadFileLocallyAndOpen(
Rename to `downloadFileLocallyAndOpenIntent`

2024-10-01 10:31 UTC, nogoodusername commented on RapidWebView/src/main/java/in/workindia/rapidwebview/activities/service/UploadService.kt
> +            Build.VERSION.SDK_INT < Build.VERSION_CODES.Q -> startForeground(90,notification)
Space missing between 90, notification.

2024-10-01 10:31 UTC, nogoodusername commented on RapidWebView/src/main/java/in/workindia/rapidwebview/utils/DownLoadUtility.kt
> +object DownLoadUtility {
Rename to `DownloadUtility`

2024-10-01 10:31 UTC, nogoodusername commented on RapidWebView/src/main/java/in/workindia/rapidwebview/utils/LocalBroadCastActionUtility.kt
> +object LocalBroadCastActionUtility {
Rename to `LoadBoardcaseActionUtility`

2024-10-01 10:31 UTC, nogoodusername commented on RapidWebView/src/main/java/in/workindia/rapidwebview/utils/Utils.kt
> +object Utils {
We will not introduce `Utils` package. Have specific class for your purpose.

2024-10-03 09:27 UTC, nogoodusername approved these changes

2024-10-03 09:47 UTC, merged